### ISSUE TITLE
does it work with phasing indels ?

### ISSUE THREAD

**Issue by zeronot** [everestial/pHASE-Stitcher#1]
Hi 
    I konw RBP only  works at SNV ,how about your tool ?

**Comment by everestial** [comment]
@zeronot : RBP from GATK (using gvcf) does phase state of the INdels too. See the comment at http://gatkforums.broadinstitute.org/gatk/discussion/45/purpose-and-operation-of-read-backed-phasing

So, you can either use gvcf method with GATK engine, or use SeCastel PHASER. My tool is designed to take the partial haplotypes from GATK engine or PHASER and stitch them together to create genome wide phase states. And, yes it works for indels but the following assumption should be held:
- you are phasing the F1 hybrid or individual from a mixed population
- you have the population frequency or partial haplotype data (generate by gatk engine or phaser) from the population samples the F1 or the hybrid was derived from
- you can relax the assumption of recombination when phasing F1 hybrids.

Makes sense? if you have some questions please let me know and/or show me your data structure so I can look at it to give you some suggestions.

Thanks,
